---
- name: "Nomad"
  block:
    - name: "Deploy Nomad Control Plane"
      ansible.builtin.import_tasks:
        file: nomad_control_plane.yml
      when:
        - nomad_enable_server
      tags:
        - nomad
        - nomad_servers

    - name: "Deploy Nomad Clients"
      ansible.builtin.import_tasks:
        file: nomad_clients.yml
      when:
        - nomad_enable_client
        - not nomad_enable_server
      tags:
        - nomad
        - nomad_clients
