---
- name: "Nomad"
  block:
    - name: "Deploy Nomad Control Plane"
      ansible.builtin.import_tasks:
        file: nomad_control_plane.yml
      when:
        - "'nomad_servers' in group_names"
      tags:
        - nomad_servers

    - name: "Deploy Nomad Clients"
      ansible.builtin.import_tasks:
        file: nomad_clients.yml
      when:
        - "'nomad_clients' in group_names"
        - "'nomad_servers' not in group_names"
      tags:
        - nomad_clients
