---
- name: Include bootstrap playbook
  ansible.builtin.import_playbook: ednxzu.hashistack.bootstrap.yml

- name: Include preflight playbook
  ansible.builtin.import_playbook: ednxzu.hashistack.preflight.yml
