---
# requirements file for ednz_cloud.hashistack
roles:
  - name: ednz_cloud.manage_repositories
    src: https://github.com/ednz-cloud/manage_repositories.git
  - name: ednz_cloud.manage_apt_packages
    src: https://github.com/ednz-cloud/manage_apt_packages.git
  - name: ednz_cloud.manage_pip_packages
    src: https://github.com/ednz-cloud/manage_pip_packages.git
  - name: ednz_cloud.install_docker
    src: https://github.com/ednz-cloud/install_docker.git
  - name: ednz_cloud.docker_systemd_service
    src: https://github.com/ednz-cloud/docker_systemd_service.git
  - name: ednz_cloud.deploy_haproxy
    src: https://github.com/ednz-cloud/deploy_haproxy.git
  - name: ednz_cloud.deploy_keepalived
    src: https://github.com/ednz-cloud/deploy_keepalived.git
