---
- name: "Vault"
  block:
    - name: "Deploy Vault Control Plane"
      ansible.builtin.import_tasks:
        file: vault_control_plane.yml
      when:
        - "'vault_servers' in group_names"
      tags:
        - vault_servers
