---
- name: "Stat global configuration file"
  ansible.builtin.stat:
    path: "{{ configuration_directory }}/{{ configuration_global_vars_file }}"
  register: _global_config_file
  delegate_to: localhost

- name: "Make sure global configuration file exists"
  ansible.builtin.assert:
    that:
      - _global_config_file.stat.exists
    fail_msg: >-
      Main configuration file {{ _global_config_file.stat.path }} was not found, cannot continue without it.
  delegate_to: localhost

- name: "Load global variables"
  ansible.builtin.include_vars:
    dir: "{{ configuration_directory }}"
    files_matching: "{{ configuration_global_vars_file }}"
    depth: 1
  delegate_to: localhost
