---
- name: "Stat group specific config file"
  ansible.builtin.stat:
    path: "{{ configuration_directory }}/{{ group_name }}/{{ configuration_global_vars_file }}"
  register: _group_config_file
  loop: "{{ group_names }}"
  loop_control:
    loop_var: group_name

- name: Load group specific variables
  ansible.builtin.include_vars:
    dir: "{{ configuration_directory }}/{{ item.group_name }}"
    files_matching: "{{ configuration_global_vars_file }}"
    depth: 1
  loop: "{{ _group_config_file.results }}"
  when: item.stat.exists
    and item.group_name in group_names
  loop_control:
    loop_var: item
  delegate_to: localhost
