---
- name: "Stat host specific config file"
  ansible.builtin.stat:
    path: "{{ configuration_directory }}/{{ group_name }}/{{ inventory_hostname }}/{{ configuration_global_vars_file }}"
  register: _host_config_file
  loop: "{{ group_names }}"
  loop_control:
    loop_var: group_name
  delegate_to: localhost

- name: Load host specific variables
  ansible.builtin.include_vars:
    dir: "{{ configuration_directory }}/{{ item.group_name }}/{{ inventory_hostname }}"
    files_matching: "{{ configuration_global_vars_file }}"
  loop: "{{ _host_config_file.results }}"
  when: item.stat.exists
  loop_control:
    loop_var: item
  delegate_to: localhost
