---
##################
# helper options #
##################

manage_pip_packages_allow_break_system_packages: "{{ ansible_distribution == 'Debian' and ansible_distribution_version == '12' }}"

hashistack_configuration_directory: "{{ lookup('env', 'PWD') }}/etc/hashistack"
hashistack_sub_configuration_directories:
  secrets: "{{ hashistack_configuration_directory }}/secrets"
  certificates: "{{ hashistack_configuration_directory }}/certificates"
  nomad_servers: "{{ hashistack_configuration_directory }}/nomad_servers"
  vault_servers: "{{ hashistack_configuration_directory }}/vault_servers"
  consul_servers: "{{ hashistack_configuration_directory }}/consul_servers"

hashistack_configuration_global_vars_file: "globals.yml"
hashistack_configuration_credentials_vars_file: "credentials.yml"

hashistack_remote_config_dir: "/etc/hashistack"
hashistack_remote_log_dir: "/var/log/hashistack"

###################
# support options #
################# #

hashistack_supported_distributions:
  - ubuntu
  - debian

hashistack_supported_distribution_versions:
  debian:
    - "11"
    - "12"
  ubuntu:
    - "20.04"
    - "22.04"

preflight_enable_host_ntp_checks: true
haproxy_required_ports: [80, 443]
vault_required_ports: [8200, 8201]
consul_required_ports: [8300, 8301, 8302, 8500, 8501, 8502, 8503, 8600]
nomad_required_ports: [4646, 4647, 4648]

target: all, !deployment
