---
##################
# helper options #
##################

# manage_pip_packages_allow_break_system_packages: true

vault_versions:
  host: "{{ vault_version if vault_version != 'latest' else vault_version + '*' }}"
  docker: "{{ vault_version }}"

consul_versions:
  host: "{{ consul_version if consul_version != 'latest' else consul_version + '*' }}"
  docker: "{{ consul_version }}"

nomad_versions:
  host: "{{ nomad_version if nomad_version != 'latest' else nomad_version + '*' }}"
  docker: "{{ nomad_version }}"

configuration_directory: "{{ lookup('env', 'PWD') }}/etc/hashistack"
sub_configuration_directories:
  certificates: "{{ configuration_directory }}/certificates"
  nomad_servers: "{{ configuration_directory }}/nomad_servers"
  vault_servers: "{{ configuration_directory }}/vault_servers"
  consul_servers: "{{ configuration_directory }}/consul_servers"

configuration_global_vars_file: "globals.yml"

default_container_extra_volumes:
  - "/etc/timezone:/etc/timezone"
  - "/etc/localtime:/etc/localtime"

###################
# support options #
################# #

hashistack_supported_distributions:
  - ubuntu
  - debian

hashistack_supported_distribution_versions:
  debian:
    - "11"
    - "12"
  ubuntu:
    - "20.04"
    - "22.04"

preflight_enable_host_ntp_checks: true
haproxy_required_ports: [80, 443]
vault_required_ports: [8200, 8201]
consul_required_ports: [8300, 8301, 8302, 8500, 8501, 8502, 8503, 8600]
nomad_required_ports: []
