---
##########
# Consul #
##########

# hashistack_consul_config_dir:
# hashistack_consul_data_dir:
# hashistack_consul_certs_dir:
# hashistack_consul_logs_dir:
# hashistack_consul_envoy_install:
# hashistack_consul_envoy_version:
# hashistack_consul_extra_files_list:
# hashistack_consul_env_variables:

#######################
# extra configuration #
#######################

# You should prioritize adding configuration
# to the configuration entries below, this
# option should be used to add pieces of configuration not
# available through standard variables.

# hashistack_consul_extra_configuration:

###########
# general #
###########

# hashistack_consul_domain:
# hashistack_consul_datacenter:
# hashistack_consul_primary_datacenter:
# hashistack_consul_gossip_encryption_key:
# hashistack_consul_enable_script_checks:

#######################
# leave configuration #
#######################

# hashistack_consul_leave_on_terminate:
# hashistack_consul_rejoin_after_leave:

######################
# join configuration #
######################

# hashistack_consul_join_configuration:

########################
# server configuration #
########################

# hashistack_consul_enable_server:
# hashistack_consul_bootstrap_expect:

####################
# ui configuration #
####################

# hashistack_consul_ui_configuration:

#########################
# address configuration #
#########################

# hashistack_consul_bind_addr:
# hashistack_consul_advertise_addr:
# hashistack_consul_address_configuration:

#####################
# ACL configuration #
#####################

# hashistack_consul_acl_configuration:

##############################
# service mesh configuration #
##############################

# hashistack_consul_mesh_configuration:

#####################
# DNS configuration #
#####################

# hashistack_consul_dns_configuration:

################
# internal tls #
################

# hashistack_consul_enable_tls:
# hashistack_consul_tls_configuration:

###########################
# telemetry configuration #
###########################

# hashistack_consul_enable_prometheus_metrics:
# hashistack_consul_prometheus_retention_time:
# hashistack_consul_telemetry_configuration:

###########
# logging #
###########

# hashistack_consul_log_level:
# hashistack_consul_enable_log_to_file:
# hashistack_consul_log_to_file_configuration:
