---
###################
# General options #
###################

enable_vault: "yes"
enable_consul: "yes"
enable_nomad: "yes"

nomad_version: "1.8.1"
consul_version: "1.18.1"
vault_version: "1.16.2"

consul_fqdn: consul.ednz.lab
vault_fqdn: vault.ednz.lab
nomad_fqdn: nomad.ednz.lab

api_interface: "eth0"
api_interface_address: "{{ ansible_facts[api_interface]['ipv4']['address'] }}"

###################
# logging options #
###################

enable_log_to_file: true

########################
# external tls options #
########################

enable_tls_external: false
external_tls_externally_managed_certs: false

########################
# internal tls options #
########################

enable_tls_internal: false
internal_tls_externally_managed_certs: false

##########
# Consul #
##########

consul_domain: consul
consul_datacenter: dc1
consul_primary_datacenter: "{{ consul_datacenter }}"
consul_gossip_encryption_key: "{{ _credentials.consul.gossip_encryption_key }}"
consul_enable_script_checks: false

consul_extra_files_list: []
consul_extra_configuration: {}

consul_enable_tls: "{{ enable_tls_internal }}"

consul_log_level: info
#########
# Vault #
#########

# hashistack_vault_cluster_name: vault
# hashistack_vault_bind_addr: "0.0.0.0"
# hashistack_vault_cluster_addr: "{{ api_interface_address }}"
# hashistack_vault_enable_ui: true
# hashistack_vault_disable_mlock: false
# hashistack_vault_disable_cache: false

# hashistack_vault_extra_files_list: []
# hashistack_vault_extra_configuration: {}

# hashistack_vault_enable_tls: "{{ enable_tls_internal }}"

# hashistack_vault_enable_service_registration: "{{ enable_consul | bool }}"

# hashistack_vault_enable_plugins: false

# hashistack_vault_log_level: info

#########
# Nomad #
#########

# hashistack_nomad_region: global
# hashistack_nomad_datacenter: dc1

# hashistack_nomad_extra_files_list: []
# hashistack_nomad_extra_configuration: {}

# hashistack_nomad_autopilot_configuration: {}

# hashistack_nomad_driver_enable_docker: true
# hashistack_nomad_driver_enable_podman: false
# hashistack_nomad_driver_enable_raw_exec: false
# hashistack_nomad_driver_enable_java: false
# hashistack_nomad_driver_enable_qemu: false

# hashistack_nomad_driver_configuration: {}

# hashistack_nomad_log_level: info

# hashistack_nomad_enable_tls: "{{ enable_tls_internal }}"
