---
#########
# Nomad #
#########

# hashistack_nomad_config_dir:
# hashistack_nomad_data_dir:
# hashistack_nomad_certs_dir:
# hashistack_nomad_logs_dir:
# hashistack_nomad_extra_files_list:
# hashistack_nomad_env_variables:

#######################
# extra configuration #
#######################

# You should prioritize adding configuration
# to the configuration entries below, this
# option should be used to add pieces of configuration not
# available through standard variables.

# hashistack_nomad_extra_configuration:

###########
# general #
###########

# hashistack_nomad_region:
# hashistack_nomad_datacenter:

#########################
# address configuration #
#########################

# hashistack_nomad_bind_addr:
# hashistack_nomad_advertise_addr:
# hashistack_nomad_address_configuration:

###########################
# autopilot configuration #
###########################

# hashistack_nomad_autopilot_configuration:

#######################
# leave configuration #
#######################

# hashistack_nomad_leave_on_interrupt:
# hashistack_nomad_leave_on_terminate:

####################
# ui configuration #
####################

# hashistack_nomad_ui_configuration:

#########################
# drivers configuration #
#########################

# hashistack_nomad_driver_enable_docker:
# hashistack_nomad_driver_enable_podman:
# hashistack_nomad_driver_enable_raw_exec:
# hashistack_nomad_driver_enable_java:
# hashistack_nomad_driver_enable_qemu:
# hashistack_nomad_driver_configuration:

###########
# logging #
###########

# hashistack_nomad_log_level:
# hashistack_nomad_enable_log_to_file:
# hashistack_nomad_log_to_file_configuration:

#####################
# ACL configuration #
#####################

# hashistack_nomad_acl_configuration:

################
# internal tls #
################

# hashistack_nomad_enable_tls:
# hashistack_nomad_tls_configuration:

###########################
# telemetry configuration #
###########################

# hashistack_nomad_telemetry_configuration:

######################
# consul integration #
######################

# hashistack_nomad_enable_consul_integration:
# hashistack_nomad_consul_integration_configuration:
# hashistack_nomad_consul_integration_tls_configuration:
# hashistack_nomad_consul_integration_server_configuration:
# hashistack_nomad_consul_integration_client_configuration:
# hashistack_nomad_consul_integration_client_tls_configuration:

############################
# nomad vault integration #
############################

# hashistack_nomad_enable_vault_integration:
# hashistack_nomad_vault_integration_configuration:
