---
#####################################################
#                                                   #
#                Non-Editable                       #
#                                                   #
#####################################################

nomad_datacenter: dc1

###########################
# nomad ACL configuration #
###########################

nomad_acl_configuration:
  enabled: true
  token_ttl: 30s
  policy_ttl: 60s
  role_ttl: 60s

#################################
# nomad autopilot configuration #
#################################

nomad_autopilot_configuration: {}

############################
# nomad consul integration #
############################

nomad_enable_consul_integration: "{{ enable_consul | bool }}"
nomad_consul_integration_configuration: {}

############################
# nomad vault integration #
############################

nomad_enable_vault_integration: false
nomad_vault_integration_configuration: {}

#############################
# nomad leave configuration #
#############################

# node will leave the cluster if the process is stopped
# and if it is only a client
nomad_leave_on_interrupt: "{{ (('nomad_clients' in group_names) and (not 'nomad_servers' in group_names)) | bool }}"
nomad_leave_on_terminate: "{{ (('nomad_clients' in group_names) and (not 'nomad_servers' in group_names)) | bool }}"

##############################
# nomad server configuration #
##############################

nomad_server_configuration:
  enabled: "{{ 'nomad_servers' in group_names }}"
  data_dir: "{{ hashicorp_nomad_data_dir }}/server"
  encrypt: "{{ _credentials.nomad.gossip_encryption_key }}"

##############################
# nomad client configuration #
##############################

nomad_client_configuration:
  enabled: "{{ 'nomad_clients' in group_names | bool }}"
  state_dir: "{{ hashicorp_nomad_data_dir }}/client"

hashicorp_nomad_cni_plugins_install: true
hashicorp_nomad_start_service: true
hashicorp_nomad_cni_plugins_version: latest
hashicorp_nomad_cni_plugins_install_path: /opt/cni/bin
hashicorp_nomad_version: latest
hashicorp_nomad_deploy_method: host # deployment method, either host or docker
hashicorp_nomad_env_variables: {}
hashicorp_nomad_config_dir: "/etc/nomad.d"
hashicorp_nomad_data_dir: /opt/nomad
hashicorp_nomad_extra_files: false
hashicorp_nomad_extra_files_src: /tmp/extra_files
hashicorp_nomad_extra_files_dst: /etc/nomad.d/extra_files
hashicorp_nomad_configuration:
  datacenter: "{{ nomad_datacenter }}"
  bind_addr: "0.0.0.0"
  data_dir: "{{ hashicorp_nomad_data_dir }}"
  leave_on_interrupt: "{{ (('nomad_clients' in group_names) and (not 'nomad_servers' in group_names)) | bool }}"
  leave_on_terminate: "{{ (('nomad_clients' in group_names) and (not 'nomad_servers' in group_names)) | bool }}"
  acl: "{{ nomad_acl_configuration }}"
  server: "{{ nomad_server_configuration }}"
  client: "{{ nomad_client_configuration }}"
