---
#########
# Vault #
#########

# hashistack_vault_config_dir:
# hashistack_vault_data_dir:
# hashistack_vault_certs_dir:
# hashistack_vault_logs_dir:
# hashistack_vault_extra_files_list:
# hashistack_vault_env_variables:

#######################
# extra configuration #
#######################

# You should prioritize adding configuration
# to the configuration entries below, this
# option should be used to add pieces of configuration not
# available through standard variables.

# hashistack_vault_extra_configuration:

###########
# general #
###########

# hashistack_vault_cluster_name:
# hashistack_vault_bind_addr:
# hashistack_vault_cluster_addr:
# hashistack_vault_enable_ui:
# hashistack_vault_disable_mlock:
# hashistack_vault_disable_cache:

######################
# seal configuration #
######################

# hashistack_vault_seal_configuration:

#########################
# storage configuration #
#########################

# hashistack_vault_storage_configuration:

##########################
# listener configuration #
##########################

# hashistack_vault_enable_tls:
# hashistack_vault_listener_configuration:
# hashistack_vault_tls_listener_configuration:

########################
# service registration #
########################

# hashistack_vault_enable_service_registration:
# hashistack_vault_service_registration_configuration:

#########################
# plugins configuration #
#########################

# hashistack_vault_enable_plugins:
# hashistack_vault_plugins_directory:

#################
# vault logging #
#################

# hashistack_vault_log_level:
# hashistack_vault_enable_log_to_file:
# hashistack_vault_log_to_file_configuration:
