---
# handlers file for docker_systemd_service
- name: "Restart service(s)"
  ansible.builtin.service:
    name: "{{ docker_systemd_service_name }}.service"
    state: restarted
  listen: "systemctl-restart-service"
  when: docker_systemd_service_restart
    and docker_systemd_service_state != "stopped"
    and not _enable_and_start.changed
