---
# requirements file for molecule
roles:
  - name: ednz_cloud.manage_repositories
  - name: ednz_cloud.manage_apt_packages
  - name: ednz_cloud.manage_pip_packages
  - name: ednz_cloud.install_docker
  - name: ednz_cloud.docker_systemd_service

collections:
  - name: ednz_cloud.hashistack
