---
# hashistack deployment playbook
- name: "Deploy"
  hosts: all
  gather_facts: true
  become: true
  tasks:
    # - name: "Include ednxzu.hashicorp_vault"
    #   ansible.builtin.include_role:
    #     name: ednxzu.hashicorp_vault

    - name: "Test module"
      ednxzu.hashistack.vault_init:
        name: "Test"
        new: true
