---
# hashistack deployment playbook
- name: "Deploy"
  hosts: all
  strategy: linear
  gather_facts: true
  become: true
  tasks:
    - name: "Import variables"
      ansible.builtin.import_tasks:
        file: tasks/load_vars.yml

    - name: "Deploy Consul"
      ansible.builtin.import_tasks:
        file: tasks/consul/consul_deploy.yml
      when:
        - enable_consul | bool
        - "'consul_servers' in group_names"
      tags:
        - consul

    - name: "Deploy Vault"
      ansible.builtin.import_tasks:
        file: tasks/vault/vault_deploy.yml
      when:
        - enable_vault | bool
        - "'vault_servers' in group_names"
      tags:
        - vault
