---
# hashistack deployment playbook
- name: "Deploy"
  hosts: all
  strategy: linear
  gather_facts: true
  become: true
  tasks:
    - name: "Import variables"
      ansible.builtin.import_tasks:
        file: tasks/load_vars.yml

    - name: "Deploy Consul Control Plane"
      ansible.builtin.import_tasks:
        file: tasks/consul/consul_deploy.yml
      when:
        - enable_consul | bool
        - "'consul_servers' in group_names"
      tags:
        - consul

    - name: "Deploy Consul Agents"
      ansible.builtin.include_role:
        name: ednz_cloud.hashistack.hashicorp_consul
      when:
        - enable_consul | bool
        - "'consul_agents' in group_names"
      tags:
        - consul

    - name: "Deploy Haproxy & Keepalived"
      ansible.builtin.import_tasks:
        file: tasks/haproxy/haproxy_deploy.yml
      when:
        - enable_haproxy | bool
        - "'haproxy_servers' in group_names"
      tags:
        - haproxy

    - name: "Deploy Vault"
      ansible.builtin.import_tasks:
        file: tasks/vault/vault_deploy.yml
      when:
        - enable_vault | bool
        - "'vault_servers' in group_names"
      tags:
        - vault
