---
# task/uninstall file for docker_systemd_service
- name: "Remove ENV file(s) for service(s)"
  ansible.builtin.file:
    path: "{{ docker_systemd_service_sysconf_dir }}/{{ docker_systemd_service_container_name }}"
    state: absent

- name: "Disable and stop service(s)"
  ansible.builtin.systemd:
    name: '{{ docker_systemd_service_name }}.service'
    enabled: false
    state: stopped

- name: "Remove unit file(s) for service(s)"
  ansible.builtin.file:
    path: /etc/systemd/system/{{ docker_systemd_service_name }}.service
    state: absent

- name: "Reload systemd units"
  ansible.builtin.systemd:
    daemon_reload: true
  changed_when: false
